services:
  django:
    container_name: django
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=admin
      - PG_DB=postgres
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      db:
        condition: service_healthy  # Assures that the database is healthy
  db:
    container_name: db
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data
    healthcheck: # checking if database is running
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: {}